# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-lambda-cloudwatch-sns-alarms
  description: '[wip] Terraform module for creating a set of Lambda alarms and outputting to an endpoint'
  homepage: https://cloudposse.com/accelerate
  topics: ""


